#!/usr/bin/env bash
set -euo pipefail

# Agora CMS — production setup script
# Run on a fresh Linux VM to install Docker and start CMS with auto-updates.

INSTALL_DIR="${1:-/opt/agora-cms}"
REPO_URL="https://raw.githubusercontent.com/sslivins/agora-cms/main"

echo "==> Agora CMS setup (install dir: $INSTALL_DIR)"

# ── Install Docker if missing ──
if ! command -v docker &>/dev/null; then
    echo "==> Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    sudo systemctl enable --now docker
    sudo usermod -aG docker "$USER"
    echo "    Docker installed. You may need to log out and back in for group changes."
fi

# ── Create install directory ──
sudo mkdir -p "$INSTALL_DIR"
sudo chown "$USER":"$USER" "$INSTALL_DIR"
cd "$INSTALL_DIR"

# ── Download compose file ──
echo "==> Downloading docker-compose.prod.yml..."
curl -fsSL "$REPO_URL/docker-compose.prod.yml" -o docker-compose.yml

# ── Create .env if missing ──
if [ ! -f .env ]; then
    echo "==> Configuring environment..."
    echo ""

    read -rp "  Admin username [admin]: " ADMIN_USER
    ADMIN_USER="${ADMIN_USER:-admin}"

    read -rsp "  Admin password: " ADMIN_PASS
    echo ""
    while [ -z "$ADMIN_PASS" ]; do
        read -rsp "  Admin password (required): " ADMIN_PASS
        echo ""
    done

    read -rsp "  PostgreSQL password: " PG_PASS
    echo ""
    while [ -z "$PG_PASS" ]; do
        read -rsp "  PostgreSQL password (required): " PG_PASS
        echo ""
    done

    SECRET_KEY=$(openssl rand -hex 32)

    cat > .env <<EOF
# Agora CMS environment — generated by setup.sh
POSTGRES_USER=agora
POSTGRES_PASSWORD=$PG_PASS
POSTGRES_DB=agora_cms

AGORA_CMS_DATABASE_URL=postgresql+asyncpg://agora:$PG_PASS@db:5432/agora_cms
AGORA_CMS_SECRET_KEY=$SECRET_KEY
AGORA_CMS_ADMIN_USERNAME=$ADMIN_USER
AGORA_CMS_ADMIN_PASSWORD=$ADMIN_PASS
AGORA_CMS_API_KEY_ROTATION_HOURS=24
EOF

    echo ""
    echo "  .env written to $INSTALL_DIR/.env"
else
    echo "==> .env already exists, skipping."
fi

# ── Start services ──
echo "==> Starting Agora CMS..."
docker compose up -d

echo ""
echo "==> Done! CMS is running at http://$(hostname -I | awk '{print $1}'):8080"
echo "    Watchtower will auto-update the CMS image every 5 minutes."
