#!/usr/bin/env bash
set -euo pipefail

# Agora CMS — production setup script
# Run on a fresh Linux VM to install Docker and start CMS with auto-updates.

INSTALL_DIR="${1:-/opt/agora-cms}"
REPO_URL="https://raw.githubusercontent.com/sslivins/agora-cms/main"

echo "==> Agora CMS setup (install dir: $INSTALL_DIR)"

# ── Install Docker if missing ──
DOCKER_JUST_INSTALLED=false
if ! command -v docker &>/dev/null; then
    echo "==> Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    sudo systemctl enable --now docker
    sudo usermod -aG docker "$USER"
    DOCKER_JUST_INSTALLED=true
fi

# ── Create install directory ──
sudo mkdir -p "$INSTALL_DIR"
sudo chown "$USER":"$USER" "$INSTALL_DIR"
cd "$INSTALL_DIR"

# ── Download compose file ──
echo "==> Downloading docker-compose.prod.yml..."
curl -fsSL "$REPO_URL/docker-compose.prod.yml" -o docker-compose.yml

# ── Create .env if missing ──
if [ ! -f .env ]; then
    echo "==> Configuring environment..."
    echo ""

    read -rp "  Web UI admin username [admin]: " ADMIN_USER </dev/tty
    ADMIN_USER="${ADMIN_USER:-admin}"

    read -rsp "  Web UI admin password: " ADMIN_PASS </dev/tty
    echo ""
    while [ -z "$ADMIN_PASS" ]; do
        read -rsp "  Web UI admin password (required): " ADMIN_PASS </dev/tty
        echo ""
    done

    read -rsp "  PostgreSQL database password: " PG_PASS </dev/tty
    echo ""
    while [ -z "$PG_PASS" ]; do
        read -rsp "  PostgreSQL database password (required): " PG_PASS </dev/tty
        echo ""
    done

    SECRET_KEY=$(openssl rand -hex 32)

    cat > .env <<EOF
# Agora CMS environment — generated by setup.sh
POSTGRES_USER=agora
POSTGRES_PASSWORD=$PG_PASS
POSTGRES_DB=agora_cms

AGORA_CMS_DATABASE_URL=postgresql+asyncpg://agora:$PG_PASS@db:5432/agora_cms
AGORA_CMS_SECRET_KEY=$SECRET_KEY
AGORA_CMS_ADMIN_USERNAME=$ADMIN_USER
AGORA_CMS_ADMIN_PASSWORD=$ADMIN_PASS
AGORA_CMS_API_KEY_ROTATION_HOURS=24

# Uncomment to reset admin password to AGORA_CMS_ADMIN_PASSWORD on next restart
# AGORA_CMS_RESET_PASSWORD=true
EOF

    echo ""
    echo "  .env written to $INSTALL_DIR/.env"
else
    echo "==> .env already exists, skipping."
fi

# ── Start services ──
# Use sudo if current user can't access Docker socket
if docker info &>/dev/null; then
    COMPOSE="docker compose"
else
    COMPOSE="sudo docker compose"
fi

echo "==> Starting Agora CMS..."
$COMPOSE up -d

echo ""
echo "==> Done! CMS is running at http://$(hostname -I | awk '{print $1}'):8080"
echo "    Watchtower will auto-update the CMS image every 5 minutes."
if [ "$DOCKER_JUST_INSTALLED" = true ]; then
    echo ""
    echo "    Note: Log out and back in so you can run 'docker compose' without sudo."
fi
