"""image provisioning: base_images + provisioned_images + JobType extension

Browser-driven Pi image provisioning (Option E).  The CMS keeps a
per-tenant cache of upstream Pi base images in Azure Blob, and on
demand produces per-fleet provisioned ``.img.xz`` files with the
device API key dropped onto the FAT boot partition.

This migration is **schema-only** — it adds two tables and two
``JobType`` enum values that subsequent PRs (worker handlers, API,
UI) build on top of.  The new types route through the existing
``jobs`` / ``job_outbox`` machinery, so no new queue, scheduler,
or worker process is required.

Lifecycle / nullability rationale
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Both rows are inserted by the API in an *intent* state
(``status='importing'`` / ``'provisioning'``) **before** the worker
has done its work.  The catalog SHA256, blob path, output size, etc.,
are not yet known at insert time — those are populated by the worker
on success.  All such fields are therefore nullable.  A non-null
``status`` distinguishes the provisional row from a completed one.

The handlers (PR 3) only flip ``status`` to ``'failed'`` when retries
are exhausted (or for explicit non-retryable errors like SHA mismatch),
so transient blips re-run the same row instead of orphaning it.

Postgres enum extension
~~~~~~~~~~~~~~~~~~~~~~~

``ALTER TYPE jobtype ADD VALUE IF NOT EXISTS '...'`` is allowed inside
a transaction on Postgres 12+, which we already require (see
``0015_slideshow_slides.py`` for prior art).  On SQLite the migration
is a no-op for the enum step — the test fixture builds the schema via
``Base.metadata.create_all``, which picks up the new enum members
automatically.

device_id is String(64), not UUID
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

``devices.id`` is a Pi serial number stored as ``String(64)`` (see
``cms/models/device.py``), not a UUID.  Foreign keys onto it must
match that type or Postgres will reject the migration.

Revision ID: 0017
Revises: 0016
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = "0017"
down_revision = "0016"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    # Extend the existing ``jobtype`` enum on Postgres.  On SQLite, the
    # enum is just a CHECK constraint generated by ``create_all`` from
    # the Python enum at fixture setup time, so it picks the new values
    # up automatically.
    if is_postgres:
        op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'IMAGE_IMPORT'")
        op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'IMAGE_PROVISION'")

    # Per-tenant catalog cache.  One row per (variant, version) the
    # admin has imported.  Status drives UX in the API/UI.
    op.create_table(
        "base_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("variant", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        # Populated by the worker on import success.  Nullable until
        # then so the API can insert an ``importing`` row before the
        # download/verify/upload work has run.
        sa.Column("sha256", sa.Text(), nullable=True),
        sa.Column("blob_path", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True),
        # Audit only — keep the row if the user is later deleted.
        sa.Column("imported_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_default",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        # importing | ready | failed
        sa.Column("status", sa.Text(), nullable=False, server_default="importing"),
        sa.Column("error_message", sa.Text(), nullable=False, server_default=""),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["imported_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("variant", "version", name="uq_base_images_variant_version"),
    )
    op.create_index(
        "ix_base_images_status", "base_images", ["status"], unique=False,
    )

    # Per-build audit row.  ``fleet_env_payload`` holds the encrypted
    # bytes the worker injects into the boot partition.  Encryption is
    # the API endpoint's responsibility (PR 4) — at this layer it is
    # opaque ciphertext.  Nullable for ``IMAGE_IMPORT`` flows that never
    # touch a provisioned row.
    op.create_table(
        "provisioned_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("base_image_id", sa.UUID(), nullable=False),
        # Pi serial / String(64) — matches ``devices.id``.
        sa.Column("device_id", sa.String(length=64), nullable=True),
        # Populated by the worker on provision success.
        sa.Column("output_sha256", sa.Text(), nullable=True),
        sa.Column("output_size", sa.BigInteger(), nullable=True),
        sa.Column("blob_path", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("built_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("built_by", sa.UUID(), nullable=True),
        # Encrypted at the application layer (PR 4).  Nullable so an
        # unprivileged caller can't insert a row without one, and so a
        # post-success ``UPDATE ... SET fleet_env_payload = NULL`` can
        # zero it after the build completes if we choose to.
        sa.Column("fleet_env_payload", sa.LargeBinary(), nullable=True),
        # Output filename the admin chose ('agora-pi5-fleet42.img.xz').
        # Validated by the imager pipeline (PR 1) before use.
        sa.Column("output_name", sa.Text(), nullable=False),
        # provisioning | ready | failed | expired
        sa.Column("status", sa.Text(), nullable=False, server_default="provisioning"),
        sa.Column("error_message", sa.Text(), nullable=False, server_default=""),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_image_id"], ["base_images.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["built_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_provisioned_images_status",
        "provisioned_images",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_provisioned_images_expires_at",
        "provisioned_images",
        ["expires_at"],
        unique=False,
    )


def downgrade() -> None:
    # Postgres ``ALTER TYPE ... DROP VALUE`` is not supported and
    # rebuilding the enum requires a column swap of every consumer
    # column.  This is a one-way migration; a true downgrade would
    # need to be paired with code that no longer references the new
    # values.
    raise NotImplementedError("downgrade of 0017 is not supported")
