"""provisioned_images: decouple from base_images, add job FK + history surface

Two operator-visible bugs on the Imager tab motivate this migration:

1. **Base-image delete refused as "in use".** A built ``.img.xz`` is
   fully self-contained (the imager pipeline decompresses the base,
   injects ``/boot/firmware/agora-fleet.env``, and recompresses to a
   brand-new blob -- the base image has zero runtime relationship to
   the artifact after build). The pre-existing
   ``provisioned_images.base_image_id`` FK was ``RESTRICT``, so any
   build performed against a base permanently blocked deleting that
   base. We flip the FK to ``SET NULL`` and add a denormalized
   ``base_variant`` / ``base_version`` snapshot so the audit trail
   ("which base did this build come from?") survives after the base
   row is gone.

2. **Built images vanished from the UI.** The UI only exposed the
   in-flight build job's one-shot download link; once you navigated
   away there was no way back to the row. The new
   ``GET /api/imager/provisioned-images`` list endpoint joins
   ``provisioned_images`` to its producing ``IMAGE_PROVISION`` job to
   surface ``download_job_id`` (so the existing
   ``/download/{job_id}`` redirect can re-mint a fresh SAS on each
   click). Adding a denormalized ``provisioning_job_id`` FK avoids a
   reverse join through ``jobs.target_id`` on every list call. Also
   ``SET NULL``: a future jobs-table sweep must not cascade-destroy
   the audit row.

Backfill:

* ``base_variant`` / ``base_version`` populated from the referenced
  ``base_images`` row (best-effort -- tolerant of missing FK).
* ``provisioning_job_id`` populated by joining
  ``jobs.target_id == provisioned_images.id AND jobs.type =
  'IMAGE_PROVISION'`` (one-to-one in practice; if multiple jobs
  match -- e.g. retries -- we take the latest).

Revision ID: 0021
Revises: 0020
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = "0021"
down_revision = "0020"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Add denormalized snapshot + new job FK columns (nullable).
    op.add_column(
        "provisioned_images",
        sa.Column("base_variant", sa.Text(), nullable=True),
    )
    op.add_column(
        "provisioned_images",
        sa.Column("base_version", sa.Text(), nullable=True),
    )
    op.add_column(
        "provisioned_images",
        sa.Column("provisioning_job_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=True),
    )

    # 2. Backfill snapshot from base_images.
    op.execute(
        """
        UPDATE provisioned_images pi
        SET base_variant = bi.variant,
            base_version = bi.version
        FROM base_images bi
        WHERE pi.base_image_id = bi.id
          AND pi.base_image_id IS NOT NULL
        """
    )

    # 3. Backfill provisioning_job_id from jobs (one row per pi in
    #    practice -- if there's more than one we take the latest).
    op.execute(
        """
        UPDATE provisioned_images pi
        SET provisioning_job_id = j.id
        FROM (
            SELECT DISTINCT ON (target_id) id, target_id
            FROM jobs
            WHERE type = 'image_provision'
            ORDER BY target_id, created_at DESC
        ) j
        WHERE j.target_id = pi.id
        """
    )

    # 4. Add the FK on provisioning_job_id with SET NULL.
    op.create_foreign_key(
        "fk_provisioned_images_provisioning_job_id",
        "provisioned_images",
        "jobs",
        ["provisioning_job_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # 5. Flip base_image_id FK from RESTRICT to SET NULL, and make
    #    the column nullable. Drop+recreate the constraint by name.
    #
    # PG names autogenerated FKs as ``<table>_<col>_fkey``. The
    # original column was created in 0017 with ondelete="RESTRICT".
    op.drop_constraint(
        "provisioned_images_base_image_id_fkey",
        "provisioned_images",
        type_="foreignkey",
    )
    op.alter_column(
        "provisioned_images",
        "base_image_id",
        nullable=True,
    )
    op.create_foreign_key(
        "provisioned_images_base_image_id_fkey",
        "provisioned_images",
        "base_images",
        ["base_image_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    raise NotImplementedError(
        "downgrade not implemented; restore from backup if rollback required"
    )
