"""Add VOICE_SYNTHESIS to the jobtype enum.

Migration 0063 added the ``VOICE_ANNOUNCEMENT`` value to ``assettype`` and
correctly reused the existing ``jobstatus`` type, but it never extended the
``jobtype`` enum for the new ``JobType.VOICE_SYNTHESIS`` member added in
``shared/models/job.py``. Every voice-announcement create/update therefore
failed at ``enqueue_job`` time with::

    asyncpg.exceptions.InvalidTextRepresentationError:
    invalid input value for enum jobtype: "VOICE_SYNTHESIS"

As with 0017, the value is added in the SQLAlchemy enum *name* form
(uppercase) because SQLAlchemy persists enum names, not ``.value`` strings.
On SQLite the enum is a CHECK constraint generated by ``create_all`` from the
Python enum at fixture setup time, so it picks the value up automatically and
this step is a no-op.

Revision ID: 0064
Revises: 0063
"""

from __future__ import annotations

from alembic import op


revision = "0064"
down_revision = "0063"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'VOICE_SYNTHESIS'")


def downgrade() -> None:
    raise NotImplementedError("downgrade of 0064 is not supported")
